### ISSUE TITLE
[Bucklescript] MVP issue tracking

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#227]
No particular orders
- [x] npm dependencies
- [x] ReasonReact
- [x] Use double iframes to avoid stale dom state
- [x] Use console-feed for fetching 
- [x] Check for empty loc and don't apply the special loc converting. eg: `open React`;
- [x] Use reflex for a more well organized panes setup 
- [x] Should check for frame's readiness before sending messages
- [x] [your ideas here]
